name: lemon_math
description: A utility library for making 2d games
version: 1.2.28
homepage: https://github.com/Jerome-Saltmarsh/dart-lemon-math

environment:
  sdk: '>=2.14.3 <3.0.0'

dev_dependencies:
  test: ^1.16.0